hi we are using git cherry-pic.........
hello guys git commands are very important......
i'm in master branch......
we are in development branch......
Welcme to devops world..........
testing pat....................
